version: '3'
services:
  fibonacci-service:
    container_name: fibonacci-service
    build: .
    ports:
      - 8080:9090
      - 8081:9091
    restart: on-failure
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
    restart: on-failure